//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.AppliedJobs = new HashSet<AppliedJob>();
            this.FavouriteJobs = new HashSet<FavouriteJob>();
        }
    
        public int JobId { get; set; }
        public string Title { get; set; }
        public Nullable<int> NoOfPost { get; set; }
        public string Description { get; set; }
        public string Qualification { get; set; }
        public string Experience { get; set; }
        public string Specialization { get; set; }
        public Nullable<System.DateTime> LastDateToApply { get; set; }
        public string Salary { get; set; }
        public string JobType { get; set; }
        public string CompanyName { get; set; }
        public string CompanyImage { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppliedJob> AppliedJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavouriteJob> FavouriteJobs { get; set; }
    }
}
